// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiyfpzzuzandijaqmoec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpeWZwenp1emFuZGlqYXFtb2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTc5MDYsImV4cCI6MjA2OTc3MzkwNn0.MvI0FEyPNUsj7YqprNq7QjcXk5Z_AZLpMO-uod_JWlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});